import { v4 as uuid } from "uuid";

export const todoDB = [
  {
    id: uuid().slice(0, 8),
    category: "Inbox",
    title: "task1",
    complete: false,
    edit: false,
  },
  {
    id: uuid().slice(0, 8),
    category: "Inbox",
    title: "task2",
    complete: false,
    edit: false,
  },
  {
    id: uuid().slice(0, 8),
    category: "Today",
    title: "task3",
    complete: true,
    edit: false,
  },
  {
    id: uuid().slice(0, 8),
    category: "Tomorrow",
    title: "task4",
    complete: false,
    edit: false,
  },
  {
    id: uuid().slice(0, 8),
    category: "Inbox",
    title: "task5",
    complete: true,
    edit: false,
  },
  {
    id: uuid().slice(0, 8),
    category: "Inbox",
    title: "task6",
    complete: false,
    edit: false,
  },
  {
    id: uuid().slice(0, 8),
    category: "Inbox",
    title: "task7",
    complete: false,
    edit: false,
  },
  {
    id: uuid().slice(0, 8),
    category: "Inbox",
    title: "task8",
    complete: true,
    edit: false,
  },
  {
    id: uuid().slice(0, 8),
    category: "Inbox",
    title: "task9",
    complete: true,
    edit: false,
  },
  {
    id: uuid().slice(0, 8),
    category: "Today",
    title: "task10",
    complete: false,
    edit: false,
  },
  {
    id: uuid().slice(0, 8),
    category: "Inbox",
    title: "task11",
    complete: false,
    edit: false,
  },
  {
    id: uuid().slice(0, 8),
    category: "Tomorrow",
    title: "task12",
    complete: false,
    edit: false,
  },
  {
    id: uuid().slice(0, 8),
    category: "Inbox",
    title: "task13",
    complete: true,
    edit: false,
  },
  {
    id: uuid().slice(0, 8),
    category: "Inbox",
    title: "task14",
    complete: false,
    edit: false,
  },
  {
    id: uuid().slice(0, 8),
    category: "Tomorrow",
    title: "task15",
    complete: true,
    edit: false,
  },
  {
    id: uuid().slice(0, 8),
    category: "Inbox",
    title: "task16",
    complete: false,
    edit: false,
  },
  {
    id: uuid().slice(0, 8),
    category: "Today",
    title: "task17",
    complete: true,
    edit: false,
  },
];
